export const INCREMENT_COUNTER = "INCREMENT_COUNTER";
export const DECREMENT_COUNTER = "DECREMENT_COUNTER";

export const GET_DOCTOR_DATA = "GET_DOCTOR_DATA";
export const ADD_DOCTOR_DATA = "ADD_DOCTOR_DATA";
export const UPDATE_DOCTOR_DATA = "UPDATE_DOCTOR_DATA";
export const DELETE_DOCTOR_DATA = "DELETE_DOCTOR_DATA";

export const GET_MADICINE_DATA = "GET_MADICINE_DATA";

export const ADD_TO_CART = "ADD_TO_CART";
export const INCR_QTY = "INCR_QTY";
export const DECR_QTY = "DECR_QTY";
export const REMOVE_ITEM = "REMOVE_ITEM";

export const SIGNUP_USER = "SIGNUP_USER";
export const LOGIN_uSER = "LOGIN_uSER";
export const RESETPASSWORD_USER = "RESETPASSWORD_USER";