export const INCREMENT_COUNTER = "INCREMENT_COUNTER";
export const DECREMENT_COUNTER = "DECREMENT_COUNTER";

export const GET_DOCTOR_DATA = "GET_DOCTOR_DATA";
export const ADD_DOCTOR_DATA = "ADD_DOCTOR_DATA";
export const UPDATE_DOCTOR_DATA = "UPDATE_DOCTOR_DATA";
export const DELETE_DOCTOR_DATA = "DELETE_DOCTOR_DATA";

